version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace/railshoeck-inertia-presentation:cached
    command: sleep infinity

volumes:
  workspace-volume: